version: "3.8"

networks:
  prometheus:
    driver: overlay
    attachable: true
  exporters:
    driver: overlay

volumes:
  prometheus:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - prometheus
      - exporters
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - prometheus:/prometheus
    depends_on:
      - node_exporter
      - cadvisor
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    networks:
      - exporters
    command:
      - '--path.rootfs=/host'
    ports:
      - 9100:9100
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    networks:
      - exporters
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    devices:
      - /dev/kmsg
