{
 "title": "Traefik",
 "description": "Traefik dashboard (data from prometheus) (based on Traefik by Thomas Cheronneau https://grafana.com/grafana/dashboards/4475)",
 "tags": [
  "prometheus",
  "traefik"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total[$__range])) by (service)"
    }
   ]
  },
  {
   "title": "Average response time by service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{}) by (service) / sum(traefik_service_request_duration_seconds_count{}) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(traefik_entrypoint_requests_total{protocol=\"http\"}[$__range])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$service response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{service=\"$service\"}[$__range])) / sum(increase(traefik_service_requests_total{service=\"$service\"}[$__range])) * 1000"
    }
   ]
  },
  {
   "title": "$service return code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\"}[$__range]))",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Total requests over $service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\"}[$__range]))",
     "legendFormat": "Total requests $service"
    }
   ]
  }
 ]
}