apiVersion: 1

datasources:
  - name: K6-InfluxDB
    type: influxdb
    access: proxy
    database: k6
    url: influxdb:8086
    editable: true
    version: 1
    org_id: 1
  - name: Prometheus
    type: prometheus
    access: proxy
    url: prometheus:9090
    editable: true
    version: 1
    org_id: 1