version: "3.8"

networks:
  prometheus:
    driver: overlay
    external:
      name: monitoring_prometheus
  influxdb:
    driver: overlay
    external:
      name: timeseries_influxdb

volumes:
  grafana:
    driver: local

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - prometheus
      - influxdb
    volumes:
      - grafana:/var/lib/grafana
      - ./datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1