version: "3.8"

networks:
  influxdb:
    driver: overlay
    attachable: true

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_DB=k6