version: "3.8"

networks:
  influxdb:
    driver: overlay
    attachable: true

volumes:
  grafana_data

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6